#ifndef PKG_CONFIG_H__
#define PKG_CONFIG_H__

#define PKG_USING_LVGL
#define PKG_LVGL_THREAD_PRIO 20
#define PKG_LVGL_THREAD_STACK_SIZE 8192
#define PKG_LVGL_DISP_REFR_PERIOD 10
#define PKG_LVGL_USING_LATEST_VERSION
#define PKG_LVGL_VER_NUM 0x99999
#define PKG_USING_LV_MUSIC_DEMO

#endif
